### ISSUE TITLE
CSS help pleassee!!

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/modularity-mindfulness#1]
Hi @charlie-quinn ! Tagging you as per request. Thanks again for all your help on this so far!

**Comment by charlie-quinn** [comment]
- [x] remove styling for your `<li>` tags
- [x] specify the Japanese text using `.font-jp`, not `.main`:
`.font-jp {
  font-family: "Noto Sans Japanese", sans-serif;
}`
- [ ] since you're already specifying the .logo's alignment on larger screens in your media query, you'll also need to specify it for smaller screens by adding it here:
`.logo {
  text-align: center;
}`
- [ ] since you're already specifying the .nav's alignment on larger screens in your media query, you'll also need to specify it for smaller screens by adding it here:
`.nav {
  text-align: center;
}`
- [ ] by removing the links' underline using `text-decoration: none`, and adding the `border-bottom` property, we have total control over how the underline styling can look:
`.nav a {
  border-bottom: .1em solid #8bc9d9;
  text-decoration: none;
  color: #005e76;
}`
- [ ] hover styling for ☝️
`.nav a:hover {
  border-color: #0084a6;
  color: #005e76;
}`
- [ ] add a class to the group of text sitting below your `.banner` image (the second `<div>` deep)
`.intro-box {
  border-bottom: .1em solid #e2e2e2;
  border-top: .1em solid #e2e2e2;
}`
- [x] adjust button styling to match:
`.btn-ghost {
  border-width: .1em;
  border-color: #8bc9d9;
  color: #005e76;
}`
- [x] adjust button's hover styling to match:
`.btn-ghost:hover {
  background-color: #8bc9d9;
  border-color: #005e76;
  color: #000;
}`
- [x] adjust footer's styling to match:
`footer {
  border-top: .1em solid #e2e2e2;
  color: #666;
}`

**Comment by cmvolden** [comment]
@charlie-quinn Thanks so much! With all that and a couple other little adjustments I was able to submit it!

**Comment by charlie-quinn** [comment]
🎉
